// enableFeaturePreview("VERSION_CATALOGS")
// enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = "xx-learning-boot"

include("xx-learning-idea-plugin-client")
include("xx-learning-idea-plugin-server")
include("xx-learning-leetcode")
include("xx-learning-hadoop")
include("xx-learning-spark")
include("xx-learning-common")
include("xx-learning-mq")
include("xx-learning-netty")
include("xx-learning-logger")
include("xx-learning-seckill")
include("xx-learning-zookeeper")
include("xx-learning-sharding")
include("xx-learning-scala")
include("xx-learning-flink")
include("xx-learning-elasticsearch")
include("xx-learning-clickhouse")
