rootProject.name = "xx-learning-boot"
include("xx-learning-idea-plugin-client")
include("xx-learning-idea-plugin-server")
include("xx-learning-leetcode")
include("xx-learning-hadoop")
include("xx-learning-spark")
include("xx-learning-common")
include("xx-learning-kafka")
include("xx-learning-netty")
include("xx-learning-logger")
include("xx-learning-seckill")
include("xx-learning-zookeeper")
